#!/usr/bin/env python3
"""Generate LinkML validation fixtures from live Mellea sources.

For every architectural class in the Mellea LinkML schema that can be
populated from real upstream data we emit one or more ``<ClassName>-<desc>.yaml``
fixtures under ``linkml/tests/data/valid/`` (and a few hand-curated
counter-examples under ``linkml/tests/data/invalid/``).

Sources of truth:

* ``mellea/backends/*.py``              -> ``BackendSpec-<family>.yaml``
* ``mellea/backends/adapters/catalog.py`` -> ``IntrinsicAdapterSpec-<name>.yaml``
* ``mellea/backends/model_ids.py``      -> ``ModelIdentifierSpec-<const>.yaml``

The generator is idempotent: re-running it overwrites the previously emitted
fixtures and removes stale auto-generated files (those carrying the
``# auto-generated`` header).  Hand-written invalid fixtures are left intact.

Usage::

    python3 linkml/scripts/gen_test_fixtures.py
    python3 linkml/scripts/gen_test_fixtures.py --repo-root /path/to/mellea
"""

from __future__ import annotations

import argparse
import ast
import sys
from collections import OrderedDict
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT_DEFAULT = Path(__file__).resolve().parents[2]
VALID_DIR_DEFAULT = REPO_ROOT_DEFAULT / "linkml" / "tests" / "data" / "valid"
INVALID_DIR_DEFAULT = REPO_ROOT_DEFAULT / "linkml" / "tests" / "data" / "invalid"

GEN_HEADER = (
    "# Auto-generated by linkml/scripts/gen_test_fixtures.py.\n"
    "# Do not edit by hand; rerun the generator to refresh.\n"
)

BACKEND_MODULE_TO_FAMILY: dict[str, str] = {
    "ollama": "OLLAMA",
    "huggingface": "HUGGINGFACE",
    "openai": "OPENAI",
    "watsonx": "WATSONX",
    "litellm": "LITELLM",
    "bedrock": "BEDROCK",
    "dummy": "DUMMY",
}


# ---------------------------------------------------------------------------
# YAML helpers
# ---------------------------------------------------------------------------


class _OrderedDumper(yaml.SafeDumper):
    def increase_indent(self, flow=False, indentless=False):
        # Force block sequences to indent under their parent key for readability.
        return super().increase_indent(flow=flow, indentless=False)


def _represent_ordered(dumper: yaml.SafeDumper, data: OrderedDict) -> Any:
    return dumper.represent_mapping("tag:yaml.org,2002:map", list(data.items()))


_OrderedDumper.add_representer(OrderedDict, _represent_ordered)


def _dump(obj: dict) -> str:
    return yaml.dump(
        obj,
        Dumper=_OrderedDumper,
        sort_keys=False,
        default_flow_style=False,
        width=100,
        allow_unicode=True,
        indent=2,
    )


def _write_fixture(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(GEN_HEADER + _dump(data), encoding="utf-8")


def _safe_stem(name: str) -> str:
    """Filename-safe slug for ``<ClassName>-<desc>.yaml``."""
    out = []
    for ch in name:
        if ch.isalnum():
            out.append(ch)
        elif ch in "-_.":
            out.append(ch)
        else:
            out.append("_")
    slug = "".join(out).strip("._-")
    return slug or "x"


# ---------------------------------------------------------------------------
# AST extractors
# ---------------------------------------------------------------------------


def _const(v: ast.expr | None) -> Any:
    if isinstance(v, ast.Constant):
        return v.value
    if isinstance(v, ast.UnaryOp) and isinstance(v.op, ast.USub):
        inner = _const(v.operand)
        if isinstance(inner, (int, float)):
            return -inner
    return None


def _kwargs(call: ast.Call) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for kw in call.keywords:
        if kw.arg is None:
            continue
        val = _const(kw.value)
        if val is not None:
            out[kw.arg] = val
    return out


def extract_intrinsics(catalog_path: Path) -> list[dict]:
    """Return ``[{name, repo_id, adapter_types?}, ...]`` from catalog.py."""
    tree = ast.parse(catalog_path.read_text(encoding="utf-8"))
    repo_consts: dict[str, str] = {}
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.Assign)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
            and isinstance(node.value, ast.Constant)
            and isinstance(node.value.value, str)
            and node.targets[0].id.endswith("_REPO")
        ):
            repo_consts[node.targets[0].id] = node.value.value

    entries: list[dict] = []
    for node in ast.walk(tree):
        if not (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Name)
            and node.func.id == "IntriniscsCatalogEntry"
        ):
            continue
        record: dict[str, Any] = {}
        for kw in node.keywords:
            if kw.arg == "name" and isinstance(kw.value, ast.Constant):
                record["name"] = kw.value.value
            elif kw.arg == "repo_id":
                if isinstance(kw.value, ast.Name):
                    record["repo_id"] = repo_consts.get(kw.value.id, kw.value.id)
                elif isinstance(kw.value, ast.Constant):
                    record["repo_id"] = kw.value.value
        if "name" in record and "repo_id" in record:
            entries.append(record)
    return entries


def extract_model_identifiers(path: Path) -> list[tuple[str, dict[str, str]]]:
    """Return ``[(constant_name, {hf_model_name, ollama_name, ...}), ...]``."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    out: list[tuple[str, dict[str, str]]] = []
    for node in tree.body:
        if not (
            isinstance(node, ast.Assign)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
            and isinstance(node.value, ast.Call)
            and isinstance(node.value.func, ast.Name)
            and node.value.func.id == "ModelIdentifier"
        ):
            continue
        kwargs = {k: v for k, v in _kwargs(node.value).items() if v is not None}
        if kwargs:
            out.append((node.targets[0].id, kwargs))
    return out


# ---------------------------------------------------------------------------
# Fixture builders
# ---------------------------------------------------------------------------


def build_backend_fixtures(repo_root: Path) -> list[tuple[str, dict]]:
    """Generate one BackendSpec fixture per backend module under mellea/backends/."""
    backends_dir = repo_root / "mellea" / "backends"
    out: list[tuple[str, dict]] = []
    for path in sorted(backends_dir.glob("*.py")):
        family = BACKEND_MODULE_TO_FAMILY.get(path.stem)
        if not family:
            continue
        body = OrderedDict(
            [
                ("id", f"mellea:backend/{path.stem}"),
                ("name", path.stem),
                ("description", f"Backend backed by mellea/backends/{path.stem}.py."),
                ("source_file", f"mellea/backends/{path.stem}.py"),
                ("module_path", f"mellea.backends.{path.stem}"),
                ("package_kind", "BACKENDS"),
                ("element_kind", "CLASS"),
                ("backend_family", family),
            ]
        )
        out.append((f"BackendSpec-{path.stem}.yaml", body))
    return out


def build_intrinsic_fixtures(repo_root: Path) -> list[tuple[str, dict]]:
    """Generate IntrinsicAdapterSpec fixtures from the adapters catalog."""
    catalog = repo_root / "mellea" / "backends" / "adapters" / "catalog.py"
    if not catalog.is_file():
        return []
    out: list[tuple[str, dict]] = []
    for entry in extract_intrinsics(catalog):
        slug = _safe_stem(entry["name"])
        body = OrderedDict(
            [
                ("id", f"mellea:intrinsic/{slug}"),
                ("name", entry["name"]),
                (
                    "description",
                    f"Intrinsic '{entry['name']}' implemented by adapters in {entry['repo_id']}.",
                ),
                ("source_file", "mellea/backends/adapters/catalog.py"),
                ("module_path", "mellea.backends.adapters.catalog"),
                ("package_kind", "BACKENDS"),
                ("element_kind", "PYDANTIC_MODEL"),
                ("repo_id", entry["repo_id"]),
                ("adapter_type", ["LORA", "ALORA"]),
            ]
        )
        out.append((f"IntrinsicAdapterSpec-{slug}.yaml", body))
    return out


def build_model_identifier_fixtures(repo_root: Path) -> list[tuple[str, dict]]:
    """Generate ModelIdentifierSpec fixtures from mellea/backends/model_ids.py."""
    path = repo_root / "mellea" / "backends" / "model_ids.py"
    if not path.is_file():
        return []
    out: list[tuple[str, dict]] = []
    schema_fields = {
        "hf_model_name",
        "ollama_name",
        "watsonx_name",
        "openai_name",
        "bedrock_name",
    }
    for const_name, fields in extract_model_identifiers(path):
        body = OrderedDict(
            [
                ("id", f"mellea:model/{const_name}"),
                ("name", const_name),
                ("description", f"Model identifier constant {const_name}."),
                ("source_file", "mellea/backends/model_ids.py"),
                ("module_path", "mellea.backends.model_ids"),
                ("package_kind", "BACKENDS"),
                ("element_kind", "DATACLASS"),
            ]
        )
        for fname in (
            "hf_model_name",
            "ollama_name",
            "watsonx_name",
            "openai_name",
            "bedrock_name",
        ):
            if fname in fields and fname in schema_fields:
                body[fname] = fields[fname]
        # Add provider list derived from which fields are populated.
        providers = []
        if fields.get("hf_model_name"):
            providers.append("huggingface")
        if fields.get("ollama_name"):
            providers.append("ollama")
        if fields.get("watsonx_name"):
            providers.append("watsonx")
        if fields.get("openai_name"):
            providers.append("openai")
        if fields.get("bedrock_name"):
            providers.append("bedrock")
        if providers:
            body["provider_name"] = providers
        out.append((f"ModelIdentifierSpec-{_safe_stem(const_name)}.yaml", body))
    return out


def build_invalid_fixtures() -> list[tuple[str, dict]]:
    """Hand-curated counter-examples for `linkml-run-examples` validation.

    Each entry violates the schema in a single, well-defined way so failures
    are diagnostic and stable across LinkML versions.
    """
    return [
        (
            "BackendSpec-missing-id.yaml",
            OrderedDict(
                [
                    # `id` is identifier+required; omitting it must fail.
                    ("name", "ollama-no-id"),
                    ("backend_family", "OLLAMA"),
                ]
            ),
        ),
        (
            "BackendSpec-bad-family.yaml",
            OrderedDict(
                [
                    ("id", "mellea:backend/bogus"),
                    ("name", "bogus"),
                    # NOT_A_REAL_FAMILY is not in BackendFamilyEnum.
                    ("backend_family", "NOT_A_REAL_FAMILY"),
                ]
            ),
        ),
        (
            "IntrinsicAdapterSpec-bad-adapter.yaml",
            OrderedDict(
                [
                    ("id", "mellea:intrinsic/bad"),
                    ("name", "bad"),
                    ("repo_id", "example/bad"),
                    # GGUF is not in AdapterTypeEnum (only LORA / ALORA).
                    ("adapter_type", ["GGUF"]),
                ]
            ),
        ),
        (
            "ModelIdentifierSpec-missing-name.yaml",
            OrderedDict(
                [
                    ("id", "mellea:model/no-name"),
                    # `name` is required on NamedElement.
                    ("hf_model_name", "example/foo"),
                ]
            ),
        ),
    ]


# ---------------------------------------------------------------------------
# Cleanup helpers
# ---------------------------------------------------------------------------


def _is_generated(path: Path) -> bool:
    try:
        return path.read_text(encoding="utf-8").startswith(GEN_HEADER.splitlines()[0])
    except OSError:
        return False


def _purge_generated(directory: Path) -> int:
    removed = 0
    if not directory.is_dir():
        return 0
    for path in directory.glob("*.yaml"):
        if _is_generated(path):
            path.unlink()
            removed += 1
    return removed


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def _parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--repo-root", type=Path, default=REPO_ROOT_DEFAULT)
    p.add_argument("--valid-dir", type=Path, default=VALID_DIR_DEFAULT)
    p.add_argument("--invalid-dir", type=Path, default=INVALID_DIR_DEFAULT)
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """CLI entry point: regenerate all valid test fixtures under tests/data/."""
    args = _parse_args(list(sys.argv[1:] if argv is None else argv))
    repo_root = args.repo_root.resolve()

    purged_valid = _purge_generated(args.valid_dir)
    purged_invalid = _purge_generated(args.invalid_dir)

    valid: list[tuple[str, dict]] = []
    valid.extend(build_backend_fixtures(repo_root))
    valid.extend(build_intrinsic_fixtures(repo_root))
    valid.extend(build_model_identifier_fixtures(repo_root))

    for filename, body in valid:
        _write_fixture(args.valid_dir / filename, body)

    for filename, body in build_invalid_fixtures():
        _write_fixture(args.invalid_dir / filename, body)

    print(
        f"wrote {len(valid)} valid fixtures to {args.valid_dir} "
        f"(purged {purged_valid} stale auto-generated)\n"
        f"wrote 4 invalid fixtures to {args.invalid_dir} "
        f"(purged {purged_invalid} stale auto-generated)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
