PREFIX mellea: <https://w3id.org/lmodel/mellea/>
PREFIX linkml: <https://w3id.org/linkml/>
PREFIX schema: <http://schema.org/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX attack: <https://w3id.org/lmodel/attack/>
PREFIX common_domain_model: <https://w3id.org/lmodel/common-domain-model/>
PREFIX iso27001: <https://w3id.org/lmodel/iso27001/>
PREFIX mcp: <https://w3id.org/lmodel/mcp/>
PREFIX nexus: <https://ibm.github.io/ai-atlas-nexus/ontology/>
PREFIX spdx: <https://spdx.org/rdf/3.0.1/terms/>

SELECT
  ?check
  ?graph
  ?subject
  ?predicate WHERE {
 GRAPH ?graph {
  ?subject rdf:type mellea:FormatterSpec .
  FILTER NOT EXISTS { ?subject  schema:name ?o  }
 }
 VALUES ?check { linkml:required }
 VALUES ?predicate { schema:name }
 
}  



















## -- End of checks for FormatterSpec


## --
## Checks for ContextSpec
## --

