// Code generated by linkml gen-cpp-header. DO NOT EDIT.
#pragma once

#include <cstdint>
#include <cstring>
#include <optional>
#include <string>
#include <vector>


namespace mellea {

/// Logical package buckets used to classify Mellea source modules.
enum class PackageKindEnum {
    /// core
    CORE,
    /// stdlib
    STDLIB,
    /// backends
    BACKENDS,
    /// formatters
    FORMATTERS,
    /// helpers
    HELPERS,
    /// plugins
    PLUGINS,
    /// telemetry
    TELEMETRY,
    /// cli
    CLI,
    /// docs examples
    DOCS_EXAMPLES,
    /// test
    TEST
};

/// Convert PackageKindEnum to its string representation.
inline const char* to_string(PackageKindEnum value) {
    switch (value) {
        case PackageKindEnum::CORE: return "CORE";
        case PackageKindEnum::STDLIB: return "STDLIB";
        case PackageKindEnum::BACKENDS: return "BACKENDS";
        case PackageKindEnum::FORMATTERS: return "FORMATTERS";
        case PackageKindEnum::HELPERS: return "HELPERS";
        case PackageKindEnum::PLUGINS: return "PLUGINS";
        case PackageKindEnum::TELEMETRY: return "TELEMETRY";
        case PackageKindEnum::CLI: return "CLI";
        case PackageKindEnum::DOCS_EXAMPLES: return "DOCS_EXAMPLES";
        case PackageKindEnum::TEST: return "TEST";
    }
    return "unknown";
}

/// Parse a string into PackageKindEnum. Returns false if the string is not a valid value.
inline bool from_string(const char* str, PackageKindEnum& out) {
    if (std::strcmp(str, "CORE") == 0) { out = PackageKindEnum::CORE; return true; }
    if (std::strcmp(str, "STDLIB") == 0) { out = PackageKindEnum::STDLIB; return true; }
    if (std::strcmp(str, "BACKENDS") == 0) { out = PackageKindEnum::BACKENDS; return true; }
    if (std::strcmp(str, "FORMATTERS") == 0) { out = PackageKindEnum::FORMATTERS; return true; }
    if (std::strcmp(str, "HELPERS") == 0) { out = PackageKindEnum::HELPERS; return true; }
    if (std::strcmp(str, "PLUGINS") == 0) { out = PackageKindEnum::PLUGINS; return true; }
    if (std::strcmp(str, "TELEMETRY") == 0) { out = PackageKindEnum::TELEMETRY; return true; }
    if (std::strcmp(str, "CLI") == 0) { out = PackageKindEnum::CLI; return true; }
    if (std::strcmp(str, "DOCS_EXAMPLES") == 0) { out = PackageKindEnum::DOCS_EXAMPLES; return true; }
    if (std::strcmp(str, "TEST") == 0) { out = PackageKindEnum::TEST; return true; }
    return false;
}

/// Kind of Python declaration captured by a ModelElement entry.
enum class ElementKindEnum {
    /// class
    CLASS,
    /// enum
    ENUM,
    /// dataclass
    DATACLASS,
    /// typed dict
    TYPED_DICT,
    /// pydantic model
    PYDANTIC_MODEL,
    /// protocol
    PROTOCOL,
    /// function
    FUNCTION,
    /// mixin
    MIXIN
};

/// Convert ElementKindEnum to its string representation.
inline const char* to_string(ElementKindEnum value) {
    switch (value) {
        case ElementKindEnum::CLASS: return "CLASS";
        case ElementKindEnum::ENUM: return "ENUM";
        case ElementKindEnum::DATACLASS: return "DATACLASS";
        case ElementKindEnum::TYPED_DICT: return "TYPED_DICT";
        case ElementKindEnum::PYDANTIC_MODEL: return "PYDANTIC_MODEL";
        case ElementKindEnum::PROTOCOL: return "PROTOCOL";
        case ElementKindEnum::FUNCTION: return "FUNCTION";
        case ElementKindEnum::MIXIN: return "MIXIN";
    }
    return "unknown";
}

/// Parse a string into ElementKindEnum. Returns false if the string is not a valid value.
inline bool from_string(const char* str, ElementKindEnum& out) {
    if (std::strcmp(str, "CLASS") == 0) { out = ElementKindEnum::CLASS; return true; }
    if (std::strcmp(str, "ENUM") == 0) { out = ElementKindEnum::ENUM; return true; }
    if (std::strcmp(str, "DATACLASS") == 0) { out = ElementKindEnum::DATACLASS; return true; }
    if (std::strcmp(str, "TYPED_DICT") == 0) { out = ElementKindEnum::TYPED_DICT; return true; }
    if (std::strcmp(str, "PYDANTIC_MODEL") == 0) { out = ElementKindEnum::PYDANTIC_MODEL; return true; }
    if (std::strcmp(str, "PROTOCOL") == 0) { out = ElementKindEnum::PROTOCOL; return true; }
    if (std::strcmp(str, "FUNCTION") == 0) { out = ElementKindEnum::FUNCTION; return true; }
    if (std::strcmp(str, "MIXIN") == 0) { out = ElementKindEnum::MIXIN; return true; }
    return false;
}

/// Where in the project an element surfaces (source, API, CLI, ...).
enum class CoverageScopeEnum {
    /// source
    SOURCE,
    /// api
    API,
    /// cli
    CLI,
    /// example
    EXAMPLE,
    /// test
    TEST
};

/// Convert CoverageScopeEnum to its string representation.
inline const char* to_string(CoverageScopeEnum value) {
    switch (value) {
        case CoverageScopeEnum::SOURCE: return "SOURCE";
        case CoverageScopeEnum::API: return "API";
        case CoverageScopeEnum::CLI: return "CLI";
        case CoverageScopeEnum::EXAMPLE: return "EXAMPLE";
        case CoverageScopeEnum::TEST: return "TEST";
    }
    return "unknown";
}

/// Parse a string into CoverageScopeEnum. Returns false if the string is not a valid value.
inline bool from_string(const char* str, CoverageScopeEnum& out) {
    if (std::strcmp(str, "SOURCE") == 0) { out = CoverageScopeEnum::SOURCE; return true; }
    if (std::strcmp(str, "API") == 0) { out = CoverageScopeEnum::API; return true; }
    if (std::strcmp(str, "CLI") == 0) { out = CoverageScopeEnum::CLI; return true; }
    if (std::strcmp(str, "EXAMPLE") == 0) { out = CoverageScopeEnum::EXAMPLE; return true; }
    if (std::strcmp(str, "TEST") == 0) { out = CoverageScopeEnum::TEST; return true; }
    return false;
}

/// Whether a Mellea context preserves linear ordering or not.
enum class ContextLinearityEnum {
    /// Sequential, ordered history.
    LINEAR,
    /// Tree- or graph-shaped history.
    NON_LINEAR
};

/// Convert ContextLinearityEnum to its string representation.
inline const char* to_string(ContextLinearityEnum value) {
    switch (value) {
        case ContextLinearityEnum::LINEAR: return "LINEAR";
        case ContextLinearityEnum::NON_LINEAR: return "NON_LINEAR";
    }
    return "unknown";
}

/// Parse a string into ContextLinearityEnum. Returns false if the string is not a valid value.
inline bool from_string(const char* str, ContextLinearityEnum& out) {
    if (std::strcmp(str, "LINEAR") == 0) { out = ContextLinearityEnum::LINEAR; return true; }
    if (std::strcmp(str, "NON_LINEAR") == 0) { out = ContextLinearityEnum::NON_LINEAR; return true; }
    return false;
}

/// High-level category of a Mellea stdlib component.
enum class ComponentCategoryEnum {
    /// instruction
    INSTRUCTION,
    /// message
    MESSAGE,
    /// tool message
    TOOL_MESSAGE,
    /// document
    DOCUMENT,
    /// intrinsic
    INTRINSIC,
    /// mobject
    MOBJECT,
    /// query
    QUERY,
    /// transform
    TRANSFORM,
    /// genstub
    GENSTUB,
    /// requirement
    REQUIREMENT,
    /// stream event
    STREAM_EVENT
};

/// Convert ComponentCategoryEnum to its string representation.
inline const char* to_string(ComponentCategoryEnum value) {
    switch (value) {
        case ComponentCategoryEnum::INSTRUCTION: return "INSTRUCTION";
        case ComponentCategoryEnum::MESSAGE: return "MESSAGE";
        case ComponentCategoryEnum::TOOL_MESSAGE: return "TOOL_MESSAGE";
        case ComponentCategoryEnum::DOCUMENT: return "DOCUMENT";
        case ComponentCategoryEnum::INTRINSIC: return "INTRINSIC";
        case ComponentCategoryEnum::MOBJECT: return "MOBJECT";
        case ComponentCategoryEnum::QUERY: return "QUERY";
        case ComponentCategoryEnum::TRANSFORM: return "TRANSFORM";
        case ComponentCategoryEnum::GENSTUB: return "GENSTUB";
        case ComponentCategoryEnum::REQUIREMENT: return "REQUIREMENT";
        case ComponentCategoryEnum::STREAM_EVENT: return "STREAM_EVENT";
    }
    return "unknown";
}

/// Parse a string into ComponentCategoryEnum. Returns false if the string is not a valid value.
inline bool from_string(const char* str, ComponentCategoryEnum& out) {
    if (std::strcmp(str, "INSTRUCTION") == 0) { out = ComponentCategoryEnum::INSTRUCTION; return true; }
    if (std::strcmp(str, "MESSAGE") == 0) { out = ComponentCategoryEnum::MESSAGE; return true; }
    if (std::strcmp(str, "TOOL_MESSAGE") == 0) { out = ComponentCategoryEnum::TOOL_MESSAGE; return true; }
    if (std::strcmp(str, "DOCUMENT") == 0) { out = ComponentCategoryEnum::DOCUMENT; return true; }
    if (std::strcmp(str, "INTRINSIC") == 0) { out = ComponentCategoryEnum::INTRINSIC; return true; }
    if (std::strcmp(str, "MOBJECT") == 0) { out = ComponentCategoryEnum::MOBJECT; return true; }
    if (std::strcmp(str, "QUERY") == 0) { out = ComponentCategoryEnum::QUERY; return true; }
    if (std::strcmp(str, "TRANSFORM") == 0) { out = ComponentCategoryEnum::TRANSFORM; return true; }
    if (std::strcmp(str, "GENSTUB") == 0) { out = ComponentCategoryEnum::GENSTUB; return true; }
    if (std::strcmp(str, "REQUIREMENT") == 0) { out = ComponentCategoryEnum::REQUIREMENT; return true; }
    if (std::strcmp(str, "STREAM_EVENT") == 0) { out = ComponentCategoryEnum::STREAM_EVENT; return true; }
    return false;
}

/// Direction of a wire model (HTTP request, response, or both).
enum class RequestResponseEnum {
    /// Inbound request payload.
    REQUEST,
    /// Outbound response payload.
    RESPONSE,
    /// Model used in both directions (rare).
    BOTH
};

/// Convert RequestResponseEnum to its string representation.
inline const char* to_string(RequestResponseEnum value) {
    switch (value) {
        case RequestResponseEnum::REQUEST: return "REQUEST";
        case RequestResponseEnum::RESPONSE: return "RESPONSE";
        case RequestResponseEnum::BOTH: return "BOTH";
    }
    return "unknown";
}

/// Parse a string into RequestResponseEnum. Returns false if the string is not a valid value.
inline bool from_string(const char* str, RequestResponseEnum& out) {
    if (std::strcmp(str, "REQUEST") == 0) { out = RequestResponseEnum::REQUEST; return true; }
    if (std::strcmp(str, "RESPONSE") == 0) { out = RequestResponseEnum::RESPONSE; return true; }
    if (std::strcmp(str, "BOTH") == 0) { out = RequestResponseEnum::BOTH; return true; }
    return false;
}

/// Backend families discovered under mellea/backends/.
enum class BackendFamilyEnum {
    /// Backend family backed by mellea/backends/bedrock.py.
    BEDROCK,
    /// Backend family backed by mellea/backends/dummy.py.
    DUMMY,
    /// Backend family backed by mellea/backends/huggingface.py.
    HUGGINGFACE,
    /// Backend family backed by mellea/backends/litellm.py.
    LITELLM,
    /// Backend family backed by mellea/backends/ollama.py.
    OLLAMA,
    /// Backend family backed by mellea/backends/openai.py.
    OPENAI,
    /// Backend family backed by mellea/backends/watsonx.py.
    WATSONX
};

/// Convert BackendFamilyEnum to its string representation.
inline const char* to_string(BackendFamilyEnum value) {
    switch (value) {
        case BackendFamilyEnum::BEDROCK: return "BEDROCK";
        case BackendFamilyEnum::DUMMY: return "DUMMY";
        case BackendFamilyEnum::HUGGINGFACE: return "HUGGINGFACE";
        case BackendFamilyEnum::LITELLM: return "LITELLM";
        case BackendFamilyEnum::OLLAMA: return "OLLAMA";
        case BackendFamilyEnum::OPENAI: return "OPENAI";
        case BackendFamilyEnum::WATSONX: return "WATSONX";
    }
    return "unknown";
}

/// Parse a string into BackendFamilyEnum. Returns false if the string is not a valid value.
inline bool from_string(const char* str, BackendFamilyEnum& out) {
    if (std::strcmp(str, "BEDROCK") == 0) { out = BackendFamilyEnum::BEDROCK; return true; }
    if (std::strcmp(str, "DUMMY") == 0) { out = BackendFamilyEnum::DUMMY; return true; }
    if (std::strcmp(str, "HUGGINGFACE") == 0) { out = BackendFamilyEnum::HUGGINGFACE; return true; }
    if (std::strcmp(str, "LITELLM") == 0) { out = BackendFamilyEnum::LITELLM; return true; }
    if (std::strcmp(str, "OLLAMA") == 0) { out = BackendFamilyEnum::OLLAMA; return true; }
    if (std::strcmp(str, "OPENAI") == 0) { out = BackendFamilyEnum::OPENAI; return true; }
    if (std::strcmp(str, "WATSONX") == 0) { out = BackendFamilyEnum::WATSONX; return true; }
    return false;
}

/// Execution mode of a Mellea plugin (derived from PluginMode).
enum class PluginModeEnum {
    /// sequential
    SEQUENTIAL,
    /// transform
    TRANSFORM,
    /// concurrent
    CONCURRENT,
    /// audit
    AUDIT,
    /// fire and forget
    FIRE_AND_FORGET
};

/// Convert PluginModeEnum to its string representation.
inline const char* to_string(PluginModeEnum value) {
    switch (value) {
        case PluginModeEnum::SEQUENTIAL: return "SEQUENTIAL";
        case PluginModeEnum::TRANSFORM: return "TRANSFORM";
        case PluginModeEnum::CONCURRENT: return "CONCURRENT";
        case PluginModeEnum::AUDIT: return "AUDIT";
        case PluginModeEnum::FIRE_AND_FORGET: return "FIRE_AND_FORGET";
    }
    return "unknown";
}

/// Parse a string into PluginModeEnum. Returns false if the string is not a valid value.
inline bool from_string(const char* str, PluginModeEnum& out) {
    if (std::strcmp(str, "SEQUENTIAL") == 0) { out = PluginModeEnum::SEQUENTIAL; return true; }
    if (std::strcmp(str, "TRANSFORM") == 0) { out = PluginModeEnum::TRANSFORM; return true; }
    if (std::strcmp(str, "CONCURRENT") == 0) { out = PluginModeEnum::CONCURRENT; return true; }
    if (std::strcmp(str, "AUDIT") == 0) { out = PluginModeEnum::AUDIT; return true; }
    if (std::strcmp(str, "FIRE_AND_FORGET") == 0) { out = PluginModeEnum::FIRE_AND_FORGET; return true; }
    return false;
}

/// Lifecycle hook stages (derived from HookType).
enum class HookTypeEnum {
    /// session pre init
    SESSION_PRE_INIT,
    /// session post init
    SESSION_POST_INIT,
    /// session reset
    SESSION_RESET,
    /// session cleanup
    SESSION_CLEANUP,
    /// component pre execute
    COMPONENT_PRE_EXECUTE,
    /// component post success
    COMPONENT_POST_SUCCESS,
    /// component post error
    COMPONENT_POST_ERROR,
    /// generation pre call
    GENERATION_PRE_CALL,
    /// generation post call
    GENERATION_POST_CALL,
    /// generation error
    GENERATION_ERROR,
    /// validation pre check
    VALIDATION_PRE_CHECK,
    /// validation post check
    VALIDATION_POST_CHECK,
    /// sampling loop start
    SAMPLING_LOOP_START,
    /// sampling iteration
    SAMPLING_ITERATION,
    /// sampling repair
    SAMPLING_REPAIR,
    /// sampling loop end
    SAMPLING_LOOP_END,
    /// tool pre invoke
    TOOL_PRE_INVOKE,
    /// tool post invoke
    TOOL_POST_INVOKE
};

/// Convert HookTypeEnum to its string representation.
inline const char* to_string(HookTypeEnum value) {
    switch (value) {
        case HookTypeEnum::SESSION_PRE_INIT: return "SESSION_PRE_INIT";
        case HookTypeEnum::SESSION_POST_INIT: return "SESSION_POST_INIT";
        case HookTypeEnum::SESSION_RESET: return "SESSION_RESET";
        case HookTypeEnum::SESSION_CLEANUP: return "SESSION_CLEANUP";
        case HookTypeEnum::COMPONENT_PRE_EXECUTE: return "COMPONENT_PRE_EXECUTE";
        case HookTypeEnum::COMPONENT_POST_SUCCESS: return "COMPONENT_POST_SUCCESS";
        case HookTypeEnum::COMPONENT_POST_ERROR: return "COMPONENT_POST_ERROR";
        case HookTypeEnum::GENERATION_PRE_CALL: return "GENERATION_PRE_CALL";
        case HookTypeEnum::GENERATION_POST_CALL: return "GENERATION_POST_CALL";
        case HookTypeEnum::GENERATION_ERROR: return "GENERATION_ERROR";
        case HookTypeEnum::VALIDATION_PRE_CHECK: return "VALIDATION_PRE_CHECK";
        case HookTypeEnum::VALIDATION_POST_CHECK: return "VALIDATION_POST_CHECK";
        case HookTypeEnum::SAMPLING_LOOP_START: return "SAMPLING_LOOP_START";
        case HookTypeEnum::SAMPLING_ITERATION: return "SAMPLING_ITERATION";
        case HookTypeEnum::SAMPLING_REPAIR: return "SAMPLING_REPAIR";
        case HookTypeEnum::SAMPLING_LOOP_END: return "SAMPLING_LOOP_END";
        case HookTypeEnum::TOOL_PRE_INVOKE: return "TOOL_PRE_INVOKE";
        case HookTypeEnum::TOOL_POST_INVOKE: return "TOOL_POST_INVOKE";
    }
    return "unknown";
}

/// Parse a string into HookTypeEnum. Returns false if the string is not a valid value.
inline bool from_string(const char* str, HookTypeEnum& out) {
    if (std::strcmp(str, "SESSION_PRE_INIT") == 0) { out = HookTypeEnum::SESSION_PRE_INIT; return true; }
    if (std::strcmp(str, "SESSION_POST_INIT") == 0) { out = HookTypeEnum::SESSION_POST_INIT; return true; }
    if (std::strcmp(str, "SESSION_RESET") == 0) { out = HookTypeEnum::SESSION_RESET; return true; }
    if (std::strcmp(str, "SESSION_CLEANUP") == 0) { out = HookTypeEnum::SESSION_CLEANUP; return true; }
    if (std::strcmp(str, "COMPONENT_PRE_EXECUTE") == 0) { out = HookTypeEnum::COMPONENT_PRE_EXECUTE; return true; }
    if (std::strcmp(str, "COMPONENT_POST_SUCCESS") == 0) { out = HookTypeEnum::COMPONENT_POST_SUCCESS; return true; }
    if (std::strcmp(str, "COMPONENT_POST_ERROR") == 0) { out = HookTypeEnum::COMPONENT_POST_ERROR; return true; }
    if (std::strcmp(str, "GENERATION_PRE_CALL") == 0) { out = HookTypeEnum::GENERATION_PRE_CALL; return true; }
    if (std::strcmp(str, "GENERATION_POST_CALL") == 0) { out = HookTypeEnum::GENERATION_POST_CALL; return true; }
    if (std::strcmp(str, "GENERATION_ERROR") == 0) { out = HookTypeEnum::GENERATION_ERROR; return true; }
    if (std::strcmp(str, "VALIDATION_PRE_CHECK") == 0) { out = HookTypeEnum::VALIDATION_PRE_CHECK; return true; }
    if (std::strcmp(str, "VALIDATION_POST_CHECK") == 0) { out = HookTypeEnum::VALIDATION_POST_CHECK; return true; }
    if (std::strcmp(str, "SAMPLING_LOOP_START") == 0) { out = HookTypeEnum::SAMPLING_LOOP_START; return true; }
    if (std::strcmp(str, "SAMPLING_ITERATION") == 0) { out = HookTypeEnum::SAMPLING_ITERATION; return true; }
    if (std::strcmp(str, "SAMPLING_REPAIR") == 0) { out = HookTypeEnum::SAMPLING_REPAIR; return true; }
    if (std::strcmp(str, "SAMPLING_LOOP_END") == 0) { out = HookTypeEnum::SAMPLING_LOOP_END; return true; }
    if (std::strcmp(str, "TOOL_PRE_INVOKE") == 0) { out = HookTypeEnum::TOOL_PRE_INVOKE; return true; }
    if (std::strcmp(str, "TOOL_POST_INVOKE") == 0) { out = HookTypeEnum::TOOL_POST_INVOKE; return true; }
    return false;
}

/// Adapter implementation type (derived from AdapterType).
enum class AdapterTypeEnum {
    /// lora
    LORA,
    /// alora
    ALORA
};

/// Convert AdapterTypeEnum to its string representation.
inline const char* to_string(AdapterTypeEnum value) {
    switch (value) {
        case AdapterTypeEnum::LORA: return "LORA";
        case AdapterTypeEnum::ALORA: return "ALORA";
    }
    return "unknown";
}

/// Parse a string into AdapterTypeEnum. Returns false if the string is not a valid value.
inline bool from_string(const char* str, AdapterTypeEnum& out) {
    if (std::strcmp(str, "LORA") == 0) { out = AdapterTypeEnum::LORA; return true; }
    if (std::strcmp(str, "ALORA") == 0) { out = AdapterTypeEnum::ALORA; return true; }
    return false;
}

/// Abstract base for any named, identifiable schema element.
struct NamedElement {
    /// Stable identifier for a schema element.
    std::string id;
    /// Human-readable name.
    std::string name;
    /// Narrative description of the element.
    std::optional<std::string> description = std::nullopt;
    /// Python module path where this element is defined.
    std::optional<std::string> module_path = std::nullopt;
    /// Source file relative to repository root.
    std::optional<std::string> source_file = std::nullopt;
    /// Package bucket.
    std::optional<PackageKindEnum> package_kind = std::nullopt;
    /// Kind of Python declaration.
    std::optional<ElementKindEnum> element_kind = std::nullopt;
    /// Where this element surfaces (source/API/CLI/example/test).
    std::vector<CoverageScopeEnum> coverage_scope = {};
    /// Free-form classification tags.
    std::vector<std::string> tags = {};
};


/// Top-level catalog rooting the analysed repository snapshot.
struct RepositoryCatalog : public NamedElement {
    /// Slot describing the repository root.
    std::optional<std::string> repository_root = std::nullopt;
    /// Slot describing the analyzed on.
    std::optional<std::string> analyzed_on = std::nullopt;
    /// Slot describing the includes path.
    std::vector<std::string> includes_path = {};
    /// Slot describing the excludes path.
    std::vector<std::string> excludes_path = {};
    /// Slot describing the declares element.
    std::vector<ModelElement> declares_element = {};
};


/// A logical Python package (directory) inside the repository.
struct PythonPackage : public NamedElement {
    /// Slot describing the package name.
    std::optional<std::string> package_name = std::nullopt;
    /// Slot describing the depends on package.
    std::vector<PythonPackage> depends_on_package = {};
    /// Slot describing the declares element.
    std::vector<ModelElement> declares_element = {};
};


/// Abstract base for concrete architectural elements.
struct ModelElement : public NamedElement {
};


/// Specification of a Mellea backend implementation.
struct BackendSpec : public ModelElement {
    /// Slot describing the backend family.
    std::optional<BackendFamilyEnum> backend_family = std::nullopt;
    /// Slot describing the model identifier.
    std::vector<ModelIdentifierSpec> model_identifier = {};
    /// Slot describing the default formatter.
    std::optional<FormatterSpec> default_formatter = std::nullopt;
    /// Slot describing the model options key.
    std::vector<std::string> model_options_key = {};
    /// Slot describing the supports streaming.
    std::optional<bool> supports_streaming = std::nullopt;
    /// Slot describing the supports tool calls.
    std::optional<bool> supports_tool_calls = std::nullopt;
    /// Slot describing the supports multimodal.
    std::optional<bool> supports_multimodal = std::nullopt;
};


/// Specification of an output formatter for a backend.
struct FormatterSpec : public ModelElement {
};


/// Specification of a context implementation.
struct ContextSpec : public ModelElement {
    /// Slot describing the context linearity.
    std::optional<ContextLinearityEnum> context_linearity = std::nullopt;
    /// Slot describing the stores component history.
    std::optional<bool> stores_component_history = std::nullopt;
    /// Slot describing the accepts message attachments.
    std::optional<bool> accepts_message_attachments = std::nullopt;
};


/// Specification of a Mellea session.
struct SessionSpec : public ModelElement {
    /// Slot describing the uses backend.
    std::optional<BackendSpec> uses_backend = std::nullopt;
    /// Slot describing the uses context.
    std::optional<ContextSpec> uses_context = std::nullopt;
    /// Slot describing the exposed method.
    std::vector<MethodSpec> exposed_method = {};
};


/// Specification of a Mellea stdlib component type.
struct ComponentSpec : public ModelElement {
    /// Slot describing the component category.
    std::optional<ComponentCategoryEnum> component_category = std::nullopt;
    /// Slot describing the input modality.
    std::vector<std::string> input_modality = {};
    /// Slot describing the parsed output type.
    std::optional<std::string> parsed_output_type = std::nullopt;
};


/// Specification of a requirement validator.
struct RequirementSpec : public ModelElement {
    /// Slot describing the validation style.
    std::optional<std::string> validation_style = std::nullopt;
    /// Slot describing the may trigger repair.
    std::optional<bool> may_trigger_repair = std::nullopt;
};


/// Specification of a sampling-loop strategy.
struct SamplingStrategySpec : public ModelElement {
    /// Slot describing the selection policy.
    std::optional<std::string> selection_policy = std::nullopt;
    /// Slot describing the loop budget hint.
    std::optional<int32_t> loop_budget_hint = std::nullopt;
    /// Slot describing the may trigger repair.
    std::optional<bool> may_trigger_repair = std::nullopt;
};


/// Specification of a Mellea plugin and the hooks it registers.
struct PluginSpec : public ModelElement {
    /// Slot describing the plugin mode.
    std::optional<PluginModeEnum> plugin_mode = std::nullopt;
    /// Slot describing the hook type.
    std::vector<HookTypeEnum> hook_type = {};
    /// Slot describing the payload model.
    std::vector<HookPayloadSpec> payload_model = {};
    /// Slot describing the plugin priority.
    std::optional<int32_t> plugin_priority = std::nullopt;
};


/// Specification of a hook payload model.
struct HookPayloadSpec : public ModelElement {
    /// Slot describing the hook type.
    std::vector<HookTypeEnum> hook_type = {};
    /// Slot describing the lifecycle role.
    std::optional<std::string> lifecycle_role = std::nullopt;
};


/// Specification of a telemetry metric emitted by Mellea.
struct TelemetryMetricSpec : public ModelElement {
    /// Slot describing the metric name.
    std::vector<std::string> metric_name = {};
};


/// Specification of a CLI command exposed under `m`.
struct CliCommandSpec : public ModelElement {
    /// Slot describing the command group.
    std::optional<std::string> command_group = std::nullopt;
    /// Slot describing the command path.
    std::optional<std::string> command_path = std::nullopt;
    /// Slot describing the command purpose.
    std::optional<std::string> command_purpose = std::nullopt;
    /// Slot describing the input model.
    std::vector<ApiModelSpec> input_model = {};
    /// Slot describing the output model.
    std::vector<ApiModelSpec> output_model = {};
};


/// Specification of an HTTP API wire model.
struct ApiModelSpec : public ModelElement {
    /// Slot describing the request or response.
    std::optional<RequestResponseEnum> request_or_response = std::nullopt;
    /// Slot describing the openai object type.
    std::optional<std::string> openai_object_type = std::nullopt;
    /// Slot describing the has field.
    std::vector<ApiFieldSpec> has_field = {};
};


/// Specification of a single field in an API model.
struct ApiFieldSpec : public NamedElement {
    /// Slot describing the field name.
    std::optional<std::string> field_name = std::nullopt;
    /// Slot describing the field type.
    std::optional<std::string> field_type = std::nullopt;
    /// Slot describing the required field.
    std::optional<bool> required_field = std::nullopt;
    /// Slot describing the allows null.
    std::optional<bool> allows_null = std::nullopt;
};


/// Specification of a method exposed by a runtime class.
struct MethodSpec : public NamedElement {
    /// Slot describing the method name.
    std::optional<std::string> method_name = std::nullopt;
    /// Slot describing the method signature.
    std::optional<std::string> method_signature = std::nullopt;
    /// Slot describing the lifecycle role.
    std::optional<std::string> lifecycle_role = std::nullopt;
};


/// Cross-provider identifier table for a single model.
struct ModelIdentifierSpec : public NamedElement {
    /// Slot describing the hf model name.
    std::optional<std::string> hf_model_name = std::nullopt;
    /// Slot describing the ollama name.
    std::optional<std::string> ollama_name = std::nullopt;
    /// Slot describing the watsonx name.
    std::optional<std::string> watsonx_name = std::nullopt;
    /// Slot describing the openai name.
    std::optional<std::string> openai_name = std::nullopt;
    /// Slot describing the bedrock name.
    std::optional<std::string> bedrock_name = std::nullopt;
    /// Slot describing the provider name.
    std::vector<std::string> provider_name = {};
};


/// Specification of an intrinsic adapter (LoRA / aLoRA).
struct IntrinsicAdapterSpec : public NamedElement {
    /// Slot describing the repo id.
    std::optional<std::string> repo_id = std::nullopt;
    /// Slot describing the adapter type.
    std::vector<AdapterTypeEnum> adapter_type = {};
};


} // namespace mellea
