// Code generated by linkml-golanggen. DO NOT EDIT.
package mellea

import (
	"time"
)
// Logical package buckets used to classify Mellea source modules.
type PackageKindEnum string

const (
	// core
	PackageKindEnumCORE PackageKindEnum = "CORE"
	// stdlib
	PackageKindEnumSTDLIB PackageKindEnum = "STDLIB"
	// backends
	PackageKindEnumBACKENDS PackageKindEnum = "BACKENDS"
	// formatters
	PackageKindEnumFORMATTERS PackageKindEnum = "FORMATTERS"
	// helpers
	PackageKindEnumHELPERS PackageKindEnum = "HELPERS"
	// plugins
	PackageKindEnumPLUGINS PackageKindEnum = "PLUGINS"
	// telemetry
	PackageKindEnumTELEMETRY PackageKindEnum = "TELEMETRY"
	// cli
	PackageKindEnumCLI PackageKindEnum = "CLI"
	// docs examples
	PackageKindEnumDOCSEXAMPLES PackageKindEnum = "DOCS_EXAMPLES"
	// test
	PackageKindEnumTEST PackageKindEnum = "TEST"
)
// Kind of Python declaration captured by a ModelElement entry.
type ElementKindEnum string

const (
	// class
	ElementKindEnumCLASS ElementKindEnum = "CLASS"
	// enum
	ElementKindEnumENUM ElementKindEnum = "ENUM"
	// dataclass
	ElementKindEnumDATACLASS ElementKindEnum = "DATACLASS"
	// typed dict
	ElementKindEnumTYPEDDICT ElementKindEnum = "TYPED_DICT"
	// pydantic model
	ElementKindEnumPYDANTICMODEL ElementKindEnum = "PYDANTIC_MODEL"
	// protocol
	ElementKindEnumPROTOCOL ElementKindEnum = "PROTOCOL"
	// function
	ElementKindEnumFUNCTION ElementKindEnum = "FUNCTION"
	// mixin
	ElementKindEnumMIXIN ElementKindEnum = "MIXIN"
)
// Where in the project an element surfaces (source, API, CLI, ...).
type CoverageScopeEnum string

const (
	// source
	CoverageScopeEnumSOURCE CoverageScopeEnum = "SOURCE"
	// api
	CoverageScopeEnumAPI CoverageScopeEnum = "API"
	// cli
	CoverageScopeEnumCLI CoverageScopeEnum = "CLI"
	// example
	CoverageScopeEnumEXAMPLE CoverageScopeEnum = "EXAMPLE"
	// test
	CoverageScopeEnumTEST CoverageScopeEnum = "TEST"
)
// Whether a Mellea context preserves linear ordering or not.
type ContextLinearityEnum string

const (
	// Sequential, ordered history.
	ContextLinearityEnumLINEAR ContextLinearityEnum = "LINEAR"
	// Tree- or graph-shaped history.
	ContextLinearityEnumNONLINEAR ContextLinearityEnum = "NON_LINEAR"
)
// High-level category of a Mellea stdlib component.
type ComponentCategoryEnum string

const (
	// instruction
	ComponentCategoryEnumINSTRUCTION ComponentCategoryEnum = "INSTRUCTION"
	// message
	ComponentCategoryEnumMESSAGE ComponentCategoryEnum = "MESSAGE"
	// tool message
	ComponentCategoryEnumTOOLMESSAGE ComponentCategoryEnum = "TOOL_MESSAGE"
	// document
	ComponentCategoryEnumDOCUMENT ComponentCategoryEnum = "DOCUMENT"
	// intrinsic
	ComponentCategoryEnumINTRINSIC ComponentCategoryEnum = "INTRINSIC"
	// mobject
	ComponentCategoryEnumMOBJECT ComponentCategoryEnum = "MOBJECT"
	// query
	ComponentCategoryEnumQUERY ComponentCategoryEnum = "QUERY"
	// transform
	ComponentCategoryEnumTRANSFORM ComponentCategoryEnum = "TRANSFORM"
	// genstub
	ComponentCategoryEnumGENSTUB ComponentCategoryEnum = "GENSTUB"
	// requirement
	ComponentCategoryEnumREQUIREMENT ComponentCategoryEnum = "REQUIREMENT"
	// stream event
	ComponentCategoryEnumSTREAMEVENT ComponentCategoryEnum = "STREAM_EVENT"
)
// Direction of a wire model (HTTP request, response, or both).
type RequestResponseEnum string

const (
	// Inbound request payload.
	RequestResponseEnumREQUEST RequestResponseEnum = "REQUEST"
	// Outbound response payload.
	RequestResponseEnumRESPONSE RequestResponseEnum = "RESPONSE"
	// Model used in both directions (rare).
	RequestResponseEnumBOTH RequestResponseEnum = "BOTH"
)
// Backend families discovered under mellea/backends/.
type BackendFamilyEnum string

const (
	// Backend family backed by mellea/backends/bedrock.py.
	BackendFamilyEnumBEDROCK BackendFamilyEnum = "BEDROCK"
	// Backend family backed by mellea/backends/dummy.py.
	BackendFamilyEnumDUMMY BackendFamilyEnum = "DUMMY"
	// Backend family backed by mellea/backends/huggingface.py.
	BackendFamilyEnumHUGGINGFACE BackendFamilyEnum = "HUGGINGFACE"
	// Backend family backed by mellea/backends/litellm.py.
	BackendFamilyEnumLITELLM BackendFamilyEnum = "LITELLM"
	// Backend family backed by mellea/backends/ollama.py.
	BackendFamilyEnumOLLAMA BackendFamilyEnum = "OLLAMA"
	// Backend family backed by mellea/backends/openai.py.
	BackendFamilyEnumOPENAI BackendFamilyEnum = "OPENAI"
	// Backend family backed by mellea/backends/watsonx.py.
	BackendFamilyEnumWATSONX BackendFamilyEnum = "WATSONX"
)
// Execution mode of a Mellea plugin (derived from PluginMode).
type PluginModeEnum string

const (
	// sequential
	PluginModeEnumSEQUENTIAL PluginModeEnum = "SEQUENTIAL"
	// transform
	PluginModeEnumTRANSFORM PluginModeEnum = "TRANSFORM"
	// concurrent
	PluginModeEnumCONCURRENT PluginModeEnum = "CONCURRENT"
	// audit
	PluginModeEnumAUDIT PluginModeEnum = "AUDIT"
	// fire and forget
	PluginModeEnumFIREANDFORGET PluginModeEnum = "FIRE_AND_FORGET"
)
// Lifecycle hook stages (derived from HookType).
type HookTypeEnum string

const (
	// session pre init
	HookTypeEnumSESSIONPREINIT HookTypeEnum = "SESSION_PRE_INIT"
	// session post init
	HookTypeEnumSESSIONPOSTINIT HookTypeEnum = "SESSION_POST_INIT"
	// session reset
	HookTypeEnumSESSIONRESET HookTypeEnum = "SESSION_RESET"
	// session cleanup
	HookTypeEnumSESSIONCLEANUP HookTypeEnum = "SESSION_CLEANUP"
	// component pre execute
	HookTypeEnumCOMPONENTPREEXECUTE HookTypeEnum = "COMPONENT_PRE_EXECUTE"
	// component post success
	HookTypeEnumCOMPONENTPOSTSUCCESS HookTypeEnum = "COMPONENT_POST_SUCCESS"
	// component post error
	HookTypeEnumCOMPONENTPOSTERROR HookTypeEnum = "COMPONENT_POST_ERROR"
	// generation pre call
	HookTypeEnumGENERATIONPRECALL HookTypeEnum = "GENERATION_PRE_CALL"
	// generation post call
	HookTypeEnumGENERATIONPOSTCALL HookTypeEnum = "GENERATION_POST_CALL"
	// generation error
	HookTypeEnumGENERATIONERROR HookTypeEnum = "GENERATION_ERROR"
	// validation pre check
	HookTypeEnumVALIDATIONPRECHECK HookTypeEnum = "VALIDATION_PRE_CHECK"
	// validation post check
	HookTypeEnumVALIDATIONPOSTCHECK HookTypeEnum = "VALIDATION_POST_CHECK"
	// sampling loop start
	HookTypeEnumSAMPLINGLOOPSTART HookTypeEnum = "SAMPLING_LOOP_START"
	// sampling iteration
	HookTypeEnumSAMPLINGITERATION HookTypeEnum = "SAMPLING_ITERATION"
	// sampling repair
	HookTypeEnumSAMPLINGREPAIR HookTypeEnum = "SAMPLING_REPAIR"
	// sampling loop end
	HookTypeEnumSAMPLINGLOOPEND HookTypeEnum = "SAMPLING_LOOP_END"
	// tool pre invoke
	HookTypeEnumTOOLPREINVOKE HookTypeEnum = "TOOL_PRE_INVOKE"
	// tool post invoke
	HookTypeEnumTOOLPOSTINVOKE HookTypeEnum = "TOOL_POST_INVOKE"
)
// Adapter implementation type (derived from AdapterType).
type AdapterTypeEnum string

const (
	// lora
	AdapterTypeEnumLORA AdapterTypeEnum = "LORA"
	// alora
	AdapterTypeEnumALORA AdapterTypeEnum = "ALORA"
)
// Abstract base for any named, identifiable schema element.
type NamedElement struct {
	// Stable identifier for a schema element.
	Id string `json:"id"`
	// Human-readable name.
	Name string `json:"name"`
	// Narrative description of the element.
	Description *string `json:"description,omitempty"`
	// Python module path where this element is defined.
	ModulePath *string `json:"module_path,omitempty"`
	// Source file relative to repository root.
	SourceFile *string `json:"source_file,omitempty"`
	// Package bucket.
	PackageKind PackageKindEnum `json:"package_kind,omitempty"`
	// Kind of Python declaration.
	ElementKind ElementKindEnum `json:"element_kind,omitempty"`
	// Where this element surfaces (source/API/CLI/example/test).
	CoverageScope []CoverageScopeEnum `json:"coverage_scope,omitempty"`
	// Free-form classification tags.
	Tags []string `json:"tags,omitempty"`
}

// Top-level catalog rooting the analysed repository snapshot.
type RepositoryCatalog struct {
	// Embedded types for inheritance
	NamedElement `json:",inline"`
	// Slot describing the repository root.
	RepositoryRoot *string `json:"repository_root,omitempty"`
	// Slot describing the analyzed on.
	AnalyzedOn *time.Time `json:"analyzed_on,omitempty"`
	// Slot describing the includes path.
	IncludesPath []string `json:"includes_path,omitempty"`
	// Slot describing the excludes path.
	ExcludesPath []string `json:"excludes_path,omitempty"`
	// Slot describing the declares element.
	DeclaresElement []ModelElement `json:"declares_element,omitempty"`
}

// A logical Python package (directory) inside the repository.
type PythonPackage struct {
	// Embedded types for inheritance
	NamedElement `json:",inline"`
	// Slot describing the package name.
	PackageName *string `json:"package_name,omitempty"`
	// Slot describing the depends on package.
	DependsOnPackage []PythonPackage `json:"depends_on_package,omitempty"`
	// Slot describing the declares element.
	DeclaresElement []ModelElement `json:"declares_element,omitempty"`
}

// Abstract base for concrete architectural elements.
type ModelElement struct {
	// Embedded types for inheritance
	NamedElement `json:",inline"`
}

// Specification of a Mellea backend implementation.
type BackendSpec struct {
	// Embedded types for inheritance
	ModelElement `json:",inline"`
	// Slot describing the backend family.
	BackendFamily BackendFamilyEnum `json:"backend_family,omitempty"`
	// Slot describing the model identifier.
	ModelIdentifier []ModelIdentifierSpec `json:"model_identifier,omitempty"`
	// Slot describing the default formatter.
	DefaultFormatter *FormatterSpecId `json:"default_formatter,omitempty"`
	// Slot describing the model options key.
	ModelOptionsKey []string `json:"model_options_key,omitempty"`
	// Slot describing the supports streaming.
	SupportsStreaming *bool `json:"supports_streaming,omitempty"`
	// Slot describing the supports tool calls.
	SupportsToolCalls *bool `json:"supports_tool_calls,omitempty"`
	// Slot describing the supports multimodal.
	SupportsMultimodal *bool `json:"supports_multimodal,omitempty"`
}

// Specification of an output formatter for a backend.
type FormatterSpec struct {
	// Embedded types for inheritance
	ModelElement `json:",inline"`
}

// Specification of a context implementation.
type ContextSpec struct {
	// Embedded types for inheritance
	ModelElement `json:",inline"`
	// Slot describing the context linearity.
	ContextLinearity ContextLinearityEnum `json:"context_linearity,omitempty"`
	// Slot describing the stores component history.
	StoresComponentHistory *bool `json:"stores_component_history,omitempty"`
	// Slot describing the accepts message attachments.
	AcceptsMessageAttachments *bool `json:"accepts_message_attachments,omitempty"`
}

// Specification of a Mellea session.
type SessionSpec struct {
	// Embedded types for inheritance
	ModelElement `json:",inline"`
	// Slot describing the uses backend.
	UsesBackend *BackendSpecId `json:"uses_backend,omitempty"`
	// Slot describing the uses context.
	UsesContext *ContextSpecId `json:"uses_context,omitempty"`
	// Slot describing the exposed method.
	ExposedMethod []MethodSpec `json:"exposed_method,omitempty"`
}

// Specification of a Mellea stdlib component type.
type ComponentSpec struct {
	// Embedded types for inheritance
	ModelElement `json:",inline"`
	// Slot describing the component category.
	ComponentCategory ComponentCategoryEnum `json:"component_category,omitempty"`
	// Slot describing the input modality.
	InputModality []string `json:"input_modality,omitempty"`
	// Slot describing the parsed output type.
	ParsedOutputType *string `json:"parsed_output_type,omitempty"`
}

// Specification of a requirement validator.
type RequirementSpec struct {
	// Embedded types for inheritance
	ModelElement `json:",inline"`
	// Slot describing the validation style.
	ValidationStyle *string `json:"validation_style,omitempty"`
	// Slot describing the may trigger repair.
	MayTriggerRepair *bool `json:"may_trigger_repair,omitempty"`
}

// Specification of a sampling-loop strategy.
type SamplingStrategySpec struct {
	// Embedded types for inheritance
	ModelElement `json:",inline"`
	// Slot describing the selection policy.
	SelectionPolicy *string `json:"selection_policy,omitempty"`
	// Slot describing the loop budget hint.
	LoopBudgetHint *int `json:"loop_budget_hint,omitempty"`
	// Slot describing the may trigger repair.
	MayTriggerRepair *bool `json:"may_trigger_repair,omitempty"`
}

// Specification of a Mellea plugin and the hooks it registers.
type PluginSpec struct {
	// Embedded types for inheritance
	ModelElement `json:",inline"`
	// Slot describing the plugin mode.
	PluginMode PluginModeEnum `json:"plugin_mode,omitempty"`
	// Slot describing the hook type.
	HookType []HookTypeEnum `json:"hook_type,omitempty"`
	// Slot describing the payload model.
	PayloadModel []HookPayloadSpec `json:"payload_model,omitempty"`
	// Slot describing the plugin priority.
	PluginPriority *int `json:"plugin_priority,omitempty"`
}

// Specification of a hook payload model.
type HookPayloadSpec struct {
	// Embedded types for inheritance
	ModelElement `json:",inline"`
	// Slot describing the hook type.
	HookType []HookTypeEnum `json:"hook_type,omitempty"`
	// Slot describing the lifecycle role.
	LifecycleRole *string `json:"lifecycle_role,omitempty"`
}

// Specification of a telemetry metric emitted by Mellea.
type TelemetryMetricSpec struct {
	// Embedded types for inheritance
	ModelElement `json:",inline"`
	// Slot describing the metric name.
	MetricName []string `json:"metric_name,omitempty"`
}

// Specification of a CLI command exposed under `m`.
type CliCommandSpec struct {
	// Embedded types for inheritance
	ModelElement `json:",inline"`
	// Slot describing the command group.
	CommandGroup *string `json:"command_group,omitempty"`
	// Slot describing the command path.
	CommandPath *string `json:"command_path,omitempty"`
	// Slot describing the command purpose.
	CommandPurpose *string `json:"command_purpose,omitempty"`
	// Slot describing the input model.
	InputModel []ApiModelSpec `json:"input_model,omitempty"`
	// Slot describing the output model.
	OutputModel []ApiModelSpec `json:"output_model,omitempty"`
}

// Specification of an HTTP API wire model.
type ApiModelSpec struct {
	// Embedded types for inheritance
	ModelElement `json:",inline"`
	// Slot describing the request or response.
	RequestOrResponse RequestResponseEnum `json:"request_or_response,omitempty"`
	// Slot describing the openai object type.
	OpenaiObjectType *string `json:"openai_object_type,omitempty"`
	// Slot describing the has field.
	HasField []ApiFieldSpec `json:"has_field,omitempty"`
}

// Specification of a single field in an API model.
type ApiFieldSpec struct {
	// Embedded types for inheritance
	NamedElement `json:",inline"`
	// Slot describing the field name.
	FieldName *string `json:"field_name,omitempty"`
	// Slot describing the field type.
	FieldType *string `json:"field_type,omitempty"`
	// Slot describing the required field.
	RequiredField *bool `json:"required_field,omitempty"`
	// Slot describing the allows null.
	AllowsNull *bool `json:"allows_null,omitempty"`
}

// Specification of a method exposed by a runtime class.
type MethodSpec struct {
	// Embedded types for inheritance
	NamedElement `json:",inline"`
	// Slot describing the method name.
	MethodName *string `json:"method_name,omitempty"`
	// Slot describing the method signature.
	MethodSignature *string `json:"method_signature,omitempty"`
	// Slot describing the lifecycle role.
	LifecycleRole *string `json:"lifecycle_role,omitempty"`
}

// Cross-provider identifier table for a single model.
type ModelIdentifierSpec struct {
	// Embedded types for inheritance
	NamedElement `json:",inline"`
	// Slot describing the hf model name.
	HfModelName *string `json:"hf_model_name,omitempty"`
	// Slot describing the ollama name.
	OllamaName *string `json:"ollama_name,omitempty"`
	// Slot describing the watsonx name.
	WatsonxName *string `json:"watsonx_name,omitempty"`
	// Slot describing the openai name.
	OpenaiName *string `json:"openai_name,omitempty"`
	// Slot describing the bedrock name.
	BedrockName *string `json:"bedrock_name,omitempty"`
	// Slot describing the provider name.
	ProviderName []string `json:"provider_name,omitempty"`
}

// Specification of an intrinsic adapter (LoRA / aLoRA).
type IntrinsicAdapterSpec struct {
	// Embedded types for inheritance
	NamedElement `json:",inline"`
	// Slot describing the repo id.
	RepoId *string `json:"repo_id,omitempty"`
	// Slot describing the adapter type.
	AdapterType []AdapterTypeEnum `json:"adapter_type,omitempty"`
}

type FormatterSpecId string

type BackendSpecId string

type ContextSpecId string


